In [7]:
# This code finds the common value items between the 2 arrays with the help of the numpy intersection function 
import numpy as np
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
print("a:",a)
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
print("b: ",b)
print("Common values between two arrays:")
print(np.intersect1d(a,b))

a: [1 2 3 2 3 4 3 4 5 6]
b:  [ 7  2 10  2  7  4  9  4  9  8]
Common values between two arrays:
[2 4]


In [13]:
#the use of the matrix and ange function are here in oder to create de 5X3 array 
matrix=np.array([range(i,i+11,5) for i in [1,2,3,4,5]])
matrix

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [25]:
#the goal of this cpde is to remove the common value beteween a and b 
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
def rem(c,d):
    for i in d:
        c=c[c!=i]
    return c
rem(a,b)
    

array([ 7, 15,  1,  8])

In [25]:
#This code will allow us to record the cumulatives miles you recorded each day during the trip. X will be the increment, the lazy days are the sum of the day where you cycle 0 miles

#we assume that at first there is no cycling, 
lazyday=0
def addtoarray(x):
    """This function is created in order to create a function where you could had the incremental miles you have done"""
    global distance
    global lazyday
    size=len(distance)
    if x==0:
        lazyday+=1
    if size==0:
        distance=np.append(distance,x)
    elif size==1:
        distance=np.append(distance,x+distance[-1])    
    elif size==35:
        print("You have done 35 days cycling")
    else:
        if distance[size-1]==distance[size-2] and x==0:
            print("You can't do no cycling in consecutive days")
        elif x==0 and lazyday==4:
            print("You can only do no cycling up to 4 dadys")
        else: 
            distance=np.append(distance,x+distance[-1]) 
      
            

In [2]:
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)

/Users/sarahbismuth/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


numpy.ndarray

In [3]:
print(nyc_water)

[[   1979.  7102100.     1512.      213. ]
 [   1980.  7071639.     1506.      213. ]
 [   1981.  7089241.     1309.      185. ]
 [   1982.  7109105.     1382.      194. ]
 [   1983.  7181224.     1424.      198. ]
 [   1984.  7234514.     1465.      203. ]
 [   1985.  7274054.     1326.      182. ]
 [   1986.  7319246.     1351.      185. ]
 [   1987.  7342476.     1447.      197. ]
 [   1988.  7353719.     1484.      202. ]
 [   1989.  7344175.     1402.      191. ]
 [   1990.  7335650.     1424.      194. ]
 [   1991.  7374501.     1469.      199. ]
 [   1992.  7428944.     1369.      184. ]
 [   1993.  7506166.     1368.5     182. ]
 [   1994.  7570458.     1357.7     179. ]
 [   1995.  7633040.     1325.7     174. ]
 [   1996.  7697812.     1297.9     169. ]
 [   1997.  7773443.     1205.5     155. ]
 [   1998.  7858259.     1219.5     155. ]
 [   1999.  7947660.     1237.2     156. ]
 [   2000.  8008278.     1240.4     155. ]
 [   2001.  8024963.5    1184.      148. ]
 [   2002. 

In [4]:
#this is the maximum yearly NYC consumption of water in millions on galon per day.
nyc_water[:,2]
np.max(nyc_water)

8622698.0

In [5]:
# the shape command allows us to find how many calendars year are represented within this data set.
np.shape(nyc_water)[0]

39

In [6]:
# Here is the mean and the standard deviation of the per capita daily water consumption.
f=nyc_water[:,3]
s=np.std(f)
print(s)
t=np.mean(f)
print(t)

31.51894330370624
160.30769230769232


In [7]:

pop_diff=f=nyc_water[:,1]
np.diff(pop_diff)

array([-30461. ,  17602. ,  19864. ,  72119. ,  53290. ,  39540. ,
        45192. ,  23230. ,  11243. ,  -9544. ,  -8525. ,  38851. ,
        54443. ,  77222. ,  64292. ,  62582. ,  64772. ,  75631. ,
        84816. ,  89401. ,  60618. ,  16685.5,  16685.5,  16685.5,
        16685.5,  16685.5,  16685.5,  16685.5,  16685.5,  16685.5,
        16685.5, 108965. ,  77081. ,  61281. ,  49530. ,  44512. ,
        21171. ,  85025. ])